fullnameOverride: dbc-crunchy-postgres-tools
deploymentName: dbc-crunchy-postgres

deployer:
  serviceAccount:
    enabled: true

# Enable the provisioner service account which is used to deploy services to our other namespaces (dev/test/prod)
# The tools namespace needs to be passed in so we know which namespace to install the service account in and the rolebindings get proper permissions
provisioner:
  namespace: c59ecc-tools
  serviceAccount:
    enabled: true

# Service account with fairly low permissions for the linter
linter:
  serviceAccount:
    enabled: true

networking:
  # Network policy to allow traffic from outside the namespace (like the internet)
  networkPolicy:
    enabled: true
  # Pod network policy to allow pods to accept traffic from other pods in this namespace
  podNetworkPolicy:
    enabled: true
  # Enable OpenShift route whitch allows you to host your application at a public URL
  route:
    enabled: true
    host: # eg: crunchy-postgres.apps.silver.devops.gov.bc.ca

