apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "app.fullname" . }}-allow-same-namespace
  labels: {{ include "app.labels" . | nindent 4 }}
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/name: {{ include "app.fullname" . }}
  ingress:
    - from:
        - podSelector:
            matchLabels:
              app.kubernetes.io/name: {{ .Release.Name }}-static
  policyTypes:
    - Ingress

---
{{- if .Values.apigateway.enabled }}
kind: NetworkPolicy
apiVersion: networking.k8s.io/v1
metadata:
  name: {{ include "app.fullname" . }}-allow-traffic-from-api-gateway-to-django
  labels: {{ include "app.labels" . | nindent 4 }}
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/name: {{ include "app.fullname" . }}
  ingress:
    - from:
        - namespaceSelector:
            matchLabels:
              environment: test
              name: {{ .Values.apigateway.namespace }}
    - from:
        - namespaceSelector:
            matchLabels:
              environment: prod
              name: {{ .Values.apigateway.namespace }}
{{- end }}